### ISSUE TITLE
Slider Warning on google chrome

### ISSUE THREAD

**Issue by iesman14217** [interfacesweb18-19/scrum-2-styles-multimedia-jirafas#3]
![googlewarning1](https://user-images.githubusercontent.com/43349465/48674022-46a21480-eb48-11e8-92ab-22c514a0a21f.jpg)

When I created the touchstart event on js for the slider in a "non-passive" way
google does not seem right, because it says that when you drag and drop it is not
the best way, but for creating events in passive would be very little complicated or more (for me).

In short, the code works well and the displacement is also smooth,
because of thi I decided to leave it like that. (when google says "most responsive" refers to
softer/sensitive). In Firefox it works correctly and without problems or announcements.

At the moment I leave it like this and if I will have time, I'll fix it. If someone wants to try it.
Best rewards.
-----------------------------------------------------------------------------------
Cuando creo el evento touchstart en javascript para el slider de forma "no passive"
a google no le parece bien, por que dice que cuando arrastras y sueltas no es del
todo eficiente (es verdad, se puede hacer mas suave el desplazamiento), pero para
crear los eventos en passive me sería un poco muy complicado o más. 

En definitiva, el código funciona bien y es suave también el desplazamiento por lo
que he decidido dejarlo así. (cuando google dice "more responsive" se refiere a 
más suave o más eficiente). En Firefox funciona correctamente y no da problemas ni
avisos.

De momento lo dejo así y si me sobra tiempo (que no), lo arreglaré. Si alguien quiere intentarlo
que lo haga.

Un saludo.

**Comment by pedroprieto** [comment]
Hi @iesman14217, I can't see the problem in `gh-pages`. Is it in your personal branch? What page is the problem in?

**Comment by iesman14217** [comment]
Hi, this problem will not be a problem.

But we have a HUGE problem also, i was doing this:
git add .
git commit -m
git push

and for merge doing this
git fetch origing
git merge origing/gh-pages

others team mates
git merge origin

NOW My code is broke what can i do?

Thanks in advance

**Comment by pedroprieto** [comment]
Ok, solved in class today.

Remember: to do a merge you should do:

```
git fetch origin
git merge origin/gh-pages
```
